### ISSUE TITLE
Optimierung Overpass Abfrage

### ISSUE THREAD

**Issue by se-na** [Schutz-Rettung-Zurich/srz-edi#11]
- [ ] Das Backend sollte einen Fehlerstatus zurückgeben, wenn die Overpass Abfrage nicht klappt.

Dies findet man Hier: https://github.com/Schutz-Rettung-Zurich/srz-edi/blob/d15582cdfcddcffd241c7e85e8ffa68f2d8e3708/Backend/osmchadjango/supervise/models.py#L150

- [ ] Beim Frontend kann optimiert werden, dass die Abfrage, die die Overpass Abfrage auslöst, nur einmal gesendet wird.

Dies findet man Hier: https://github.com/Schutz-Rettung-Zurich/srz-edi/blob/d15582cdfcddcffd241c7e85e8ffa68f2d8e3708/Frontend/src/pages/Home.js#L88 und https://github.com/Schutz-Rettung-Zurich/srz-edi/blob/d15582cdfcddcffd241c7e85e8ffa68f2d8e3708/Frontend/src/pages/Overview.js#L48

- [ ] Die Abfrage könnte mit einem Cash erweitert werden. Nicht nur die Antwort vom Overpass sondern die Fertig gefilterten Changesets sollen dem Filter als new hinzugefügt werden. Und inerhalb einer definierten Zeitspanne werden nur die Zugewiesenen zurückgegeben und wen die letzte Anfrage zu weit zurück liegt, wird eine neue Overpass Anfrage gesendet und mit dessen Antwort die Changesets neu gefiltert.
(Die Zuweisung der Changesets zum Filter wird bereits vorgenommen für die Statusspeicherung unbearbeitet, in Bearbeitung und Abgeschlossen, aber die Zuweisung müsste überprüft und angepasst werden, damit die Changesets zurückgegeben werden, wenn die die festgelegte Zeit noch nicht überschritten ist.)

**Comment by chnuessli** [comment]
> Dies findet man Hier:
> 
> https://github.com/Schutz-Rettung-Zurich/srz-edi/blob/d15582cdfcddcffd241c7e85e8ffa68f2d8e3708/Backend/osmchadjango/supervise/models.py#L150

Evtl hier auf die Schweizer API umstellen um Abfragen nur in der Schweiz zu machen und somit die Zuverlässigkeit zu erhöhen?

**Comment by chnuessli** [comment]
Irrelevant wegen neuem Monitoring Tool
