### ISSUE TITLE
Mehr Kantone

### ISSUE THREAD

**Issue by brawer** [Schutz-Rettung-Zurich/srz-edi#16]
Nachdem das Werkzeug ja eh schon einen Kantons-Filter hat, könnte es gleich alle 26 Kantone unterstützen? So wäre das Werkzeug auch noch für weitere Organisationen in der Schweiz brauchbar, nicht nur für S+R Zürich. Wobei ich nicht weiss, ob das einfach an der Kantons-Auswahl liegt, oder ob es da noch mehr brauchen würde.

**Comment by chnuessli** [comment]
Ich werde mir das anschauen, sollte konfigurierbar sein. Mache mal mit SG einen Test

**Comment by chnuessli** [comment]
Hey @brawer 
I've inserted all of the swiss cantons in the filter dropdown. If you take a key that's often used, it shows some changesets now.
Can you take a look and give me feedback, if this is what you requested?

**Comment by brawer** [comment]
Schaut super aus! Nur im Aargau gibt’s offenbar noch ein kleines kosmetisches Problem:

![image](https://user-images.githubusercontent.com/1527880/124109873-e5fd4700-da67-11eb-9915-5db460f46704.png)

**Comment by chnuessli** [comment]
fixed all filters and their names. successfully rolled out all cantons
