### ISSUE TITLE
Funktionieren Filter für Tags mit Doppelpunkten ?

### ISSUE THREAD

**Issue by chatelao** [Schutz-Rettung-Zurich/srz-edi#18]
Beispiel:
- "tower:type"="divinig"

Nicht funktioniert hat:
- "tower:type"="divinig"
- tower:type=divinig
- 'tower:type'='divinig'
- 'tower:type=divinig'

**Comment by chnuessli** [comment]
Das funktioniert zur Zeit noch nicht. Wir schauen wie wir das implementieren können.

**Comment by chnuessli** [comment]
Irrelevant wegen neuem Monitoring Tool
