### ISSUE TITLE
Ersatz Mapbox Karte

### ISSUE THREAD

**Issue by chnuessli** [Schutz-Rettung-Zurich/srz-edi#3]
Die Karte im Frontend könnte selber implementiert werden, um mehr Kontrolle darüber zu haben.

**Comment by chnuessli** [comment]
evtl. Leaflet ?

**Comment by brawer** [comment]
Perhaps relevant: http://www.openfiremap.de/?zoom=16&lat=47.37174&lon=8.54226 (with specific symbols for hydrants etc.)

**Comment by chnuessli** [comment]
Irrelevant wegen neuem Monitoring Tool
